checksum

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -241,15 +241,19 @@ jobs:
             # Télécharger le fichier de checksum
             curl -L -o local-php-security-checker.sha256 https://github.com/fabpot/local-php-security-checker/releases/download/v2.1.3/local-php-security-checker_linux_amd64.sha256
 
-            # Ajouter le nom du fichier au checksum
-            echo "$(cat local-php-security-checker.sha256)  local-php-security-checker" > local-php-security-checker.sha256
-
-            # Valider l'authenticité du fichier téléchargé
+            # Calculer et comparer le checksum
             echo "Vérification du checksum SHA256..."
-            sha256sum -c local-php-security-checker.sha256 || (echo "Checksum invalide !"; exit 1)
+            calculated_checksum=$(sha256sum local-php-security-checker | awk '{print $1}')
+            expected_checksum=$(cat local-php-security-checker.sha256)
+
+            if [ "$calculated_checksum" != "$expected_checksum" ]; then
+              echo "Checksum invalide !"
+              exit 1
+            fi
 
             # Rendre l'outil exécutable
             chmod +x local-php-security-checker
+
       - run:
           name: Check Dependencies
           command: ./local-php-security-checker --format=json > security-report.json
