change security approval for failed

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -251,43 +251,18 @@ jobs:
           name: Check Dependencies
           command: ./local-php-security-checker --format=json > security-report.json
       - run:
-          name: Alert on Critical Vulnerabilities
+          name: Check for Critical Vulnerabilities
           command: |
+            # Si des vulnérabilités critiques sont trouvées, échouer le job
             if grep '"severity": "critical"' security-report.json; then
-              echo "Critical vulnerability found. Requiring manual approval."
-              echo "CRITICAL VULNERABILITY DETECTED" > critical-alert.log
-              echo "approval_required=true" >> needs-approval.txt
+              echo "Critical vulnerability found. Failing the job."
+              exit 1  # Le job échoue ici si une vulnérabilité critique est trouvée
             else
               echo "No critical vulnerabilities found."
-              echo "approval_required=false" >> needs-approval.txt
             fi
       - store_artifacts:
           path: security-report.json
           destination: security-report
-      - store_artifacts:
-          path: critical-alert.log
-          destination: alerts/critical
-      - store_artifacts:
-          path: needs-approval.txt
-          destination: approval-status
-
-  security-approval:
-    type: approval
-    requires:
-      - security-check-dependencies
-    condition:
-      # Cette condition est utilisée pour vérifier le fichier qui indique si une approbation est nécessaire.
-      - run:
-          name: Check if approval is required
-          command: |
-            approval_required=$(cat approval-status/needs-approval.txt | grep approval_required | cut -d'=' -f2)
-            if [ "$approval_required" == "true" ]; then
-              echo "Manual approval is required due to critical vulnerabilities."
-            else
-              echo "No manual approval needed. Proceeding without approval."
-              exit 0  # Permet au job de passer sans approbation si aucune vulnérabilité critique n'est trouvée.
-            fi
-
 
   test-phpunit:
     executor: php-executor
@@ -391,9 +366,6 @@ workflows:
       - security-check-dependencies:
           requires:
             - build-setup
-      - security-approval:
-          requires:
-            - security-check-dependencies
       - test-phpunit:
           requires:
             - build-setup
